# Generated by Django 5.2.1 on 2025-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareingredient',
            name='side_effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincareingredient',
            name='warning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skincareingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
